# -*- coding: utf-8 -*-
"""AI/ML (PROJECT).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7AKp2NpkydRM6jwERcXMLelUauM12_j
"""

# Step 1: Install libraries (if needed)
!pip install nltk

# Step 2: Import libraries
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download('punkt')

# Step 3: Input notes
notes = """Photosynthesis converts light energy into chemical energy.
Acid rain is caused by sulfur dioxide and nitrogen oxides.
The nitrogen cycle involves fixation, nitrification, and denitrification.
"""


# Step 4: Split into sentences
sentences = sent_tokenize(notes)

# Step 5: Generate flashcards (Q/A pairs)
flashcards = []
for s in sentences:
    words = word_tokenize(s)
    question = f"What is the key idea in: '{s}'?"
    answer = " ".join(words[:5]) + "..."
    flashcards.append((question, answer))

# Step 6: Display flashcards
for q, a in flashcards:
    print("Q:", q)
    print("A:", a)
    print()